version: "3.9"
services:

  nginx:
    container_name: nginx-${PROJECT_SLUG}
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ./:/var/www/
      - ./.docker-compose/nginx/conf.d:/etc/nginx/conf.d/
      - ./.docker-compose/nginx/log:/var/log/nginx/
    networks:
      - base
    links:
      - php

  php:
    container_name: php-${PROJECT_SLUG}
    build:
      context: ./.docker-compose/php
      dockerfile: Dockerfile
      args:
        UID: "${UID}"
        GID: "${GID}"
        PHP_INI_FILE: "${PHP_INI_FILE}"
    restart: unless-stopped
    volumes:
      - ./:/var/www/
    networks:
      - base
    depends_on:
      - postgres

  postgres:
    container_name: pg-${PROJECT_SLUG}
    build:
      context: ./.docker-compose/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT_EXT}:5432"
    networks:
      - base

volumes:
  pgdata:

networks:
  base:
    driver: bridge
